server:
    address: ${SERVER_ADDR}
    port: ${SERVER_PORT}

spring:

    application:
        name: roamio

    config:
        import: optional:file:.env[.properties]

    mvc:
        static-path-pattern: /static/**

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    freemarker:
        cache: false

mybatis:
    mapper-locations: classpath:mappers/**/*.xml
    type-aliases-package: com.ssafy.roamio.*.domain
    configuration:
        map-underscore-to-camel-case: true

logging:
    level:
        com.ssafy: debug
        org.mybatis: debug