name: CI test on Pull request
on:
  pull_request:
    branches: [ 'main', 'develop' ]

jobs:
  test:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3

    - name: Set up env var
      env:
        ENV_BASE64: ${{ secrets.ENV_FILE_BASE64 }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: gradle

    - name: Create .env file
      run: |
        echo $ENV_BASE64 | base64 --decode > .env

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build